version: 0.2
phases:
  install:
    commands:
      - echo "Installing..."
      - npm install
      - tar --exclude .git --exclude .gitignore -cjv -f bundle.tar.gz .
artifacts:
  files:
    - 'bundle.tar.gz'
