version: 0.2
phases:
  install:
    commands:
      - echo "Installing..."
      - npm install
  build:
    commands:
      - mkdir -p dist
      - tar --exclude .git --exclude dist -cjv -f dist/bundle.tar.gz .
artifacts:
  files:
    - 'dist/bundle.tar.gz'
